"""add user profile and preferences tables

Revision ID: aabbbbc46502
Revises: 63a40d8ceeaf
Create Date: 2025-12-31 19:13:22.789136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aabbbbc46502'
down_revision: Union[str, None] = '63a40d8ceeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('morning_checkin_enabled', sa.Boolean(), nullable=False),
    sa.Column('morning_checkin_time', sa.Time(), nullable=False),
    sa.Column('evening_checkin_enabled', sa.Boolean(), nullable=False),
    sa.Column('evening_checkin_time', sa.Time(), nullable=False),
    sa.Column('weekly_review_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='week_day_enum', native_enum=False), nullable=False),
    sa.Column('communication_style', sa.Enum('DIRECT', 'GENTLE', 'MOTIVATING', name='communication_style_enum', native_enum=False), nullable=False),
    sa.Column('coach_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='onboarding_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vision_5_years', sa.Text(), nullable=True),
    sa.Column('current_challenge', sa.Text(), nullable=True),
    sa.Column('annual_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {id, description, life_area, priority}'),
    sa.Column('life_dashboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Object with health, work, relationships, personal_time scores (1-10)'),
    sa.Column('observed_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {pattern_type, description, confidence}'),
    sa.Column('moral_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Object with care, fairness, loyalty, authority, purity, liberty scores (0-1)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
