"""add context_type and channel to conversations

Revision ID: e7f8bc030701
Revises: 7a06b8bcb703
Create Date: 2026-02-17 22:05:43.668783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f8bc030701'
down_revision: Union[str, None] = '7a06b8bcb703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('context_type', sa.Enum('ONBOARDING_SHORT', 'ONBOARDING_LONG', 'PLANNING', 'CHECK_IN', 'REVIEW', 'FREE_CHAT', name='conversation_context_enum', native_enum=False), server_default='FREE_CHAT', nullable=False))
    op.add_column('conversations', sa.Column('channel', sa.Enum('WEB', 'WHATSAPP', name='interaction_channel_enum', native_enum=False), server_default='WEB', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'channel')
    op.drop_column('conversations', 'context_type')
    # ### end Alembic commands ###
