"""add deep onboarding models

Revision ID: 73d2b72200f3
Revises: 40c7f14ffbc4
Create Date: 2026-02-21 20:16:41.619728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d2b72200f3'
down_revision: Union[str, None] = '40c7f14ffbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_goals',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('life_area', sa.String(length=50), nullable=False, comment='LifeArea value (VARCHAR)'),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Ordering priority (lower = higher priority)'),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'REVIEW_PENDING', 'COMPLETED', 'ABANDONED', name='goal_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_goals_id'), 'annual_goals', ['id'], unique=False)
    op.create_index(op.f('ix_annual_goals_user_id'), 'annual_goals', ['user_id'], unique=False)
    op.create_table('life_area_scores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False, comment='LifeArea value (VARCHAR, no native enum)'),
    sa.Column('current_score', sa.Integer(), nullable=False, comment='Current satisfaction score 1-10'),
    sa.Column('desired_score', sa.Integer(), nullable=False, comment='Desired satisfaction score 1-10'),
    sa.Column('is_priority', sa.Boolean(), server_default='false', nullable=False, comment='Whether this area is a top priority for improvement'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_area_scores_id'), 'life_area_scores', ['id'], unique=False)
    op.create_index(op.f('ix_life_area_scores_user_id'), 'life_area_scores', ['user_id'], unique=False)
    op.create_table('onboarding_insights',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('energizing_activities', sa.ARRAY(sa.String()), nullable=True, comment='Activities that energize / what the user loves doing'),
    sa.Column('recognized_skills', sa.ARRAY(sa.String()), nullable=True, comment='Skills recognized by others / what the user is good at'),
    sa.Column('market_problems', sa.ARRAY(sa.String()), nullable=True, comment='Problems the world needs solved that the user sees'),
    sa.Column('top_values', sa.ARRAY(sa.String()), nullable=True, comment='Top 3-5 personal values identified'),
    sa.Column('value_behavior_gap', sa.Text(), nullable=True, comment='Gap between stated values and current behavior'),
    sa.Column('future_self_description', sa.Text(), nullable=True, comment='Description of ideal life in 12 months'),
    sa.Column('milestone_6months', sa.Text(), nullable=True, comment='What needs to be true at 6 months to reach the 12-month vision'),
    sa.Column('milestone_3months', sa.Text(), nullable=True, comment='What needs to be true at 3 months'),
    sa.Column('first_step', sa.Text(), nullable=True, comment='The very first concrete step toward the vision'),
    sa.Column('best_outcome', sa.Text(), nullable=True, comment='Best imaginable outcome if goals are achieved (WOOP: Outcome)'),
    sa.Column('internal_obstacle', sa.Text(), nullable=True, comment='Main internal obstacle (WOOP: Obstacle)'),
    sa.Column('if_then_plan', sa.Text(), nullable=True, comment='If [obstacle] then [plan] — implementation intention (WOOP: Plan)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_insights_id'), 'onboarding_insights', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_insights_user_id'), 'onboarding_insights', ['user_id'], unique=True)
    op.create_table('monthly_objectives',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('annual_goal_id', sa.Uuid(), nullable=True),
    sa.Column('monthly_plan_id', sa.Uuid(), nullable=True, comment='FK to monthly_plans.id (table added in M3)'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'NOT_COMPLETED', 'DROPPED', name='objective_status_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annual_goal_id'], ['annual_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_objectives_annual_goal_id'), 'monthly_objectives', ['annual_goal_id'], unique=False)
    op.create_index(op.f('ix_monthly_objectives_id'), 'monthly_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_objectives_user_id'), 'monthly_objectives', ['user_id'], unique=False)
    op.create_table('weekly_objectives',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weekly_plan_id', sa.Uuid(), nullable=True, comment='FK to weekly_plans.id (table added in M3)'),
    sa.Column('monthly_objective_id', sa.Uuid(), nullable=True),
    sa.Column('annual_goal_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('PRIMARY', 'SECONDARY', name='objective_priority_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'NOT_COMPLETED', 'DROPPED', name='objective_status_enum', native_enum=False), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True, comment='LifeArea value (VARCHAR, nullable)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annual_goal_id'], ['annual_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monthly_objective_id'], ['monthly_objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_objectives_annual_goal_id'), 'weekly_objectives', ['annual_goal_id'], unique=False)
    op.create_index(op.f('ix_weekly_objectives_id'), 'weekly_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_objectives_monthly_objective_id'), 'weekly_objectives', ['monthly_objective_id'], unique=False)
    op.create_index(op.f('ix_weekly_objectives_user_id'), 'weekly_objectives', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_objectives_user_id'), table_name='weekly_objectives')
    op.drop_index(op.f('ix_weekly_objectives_monthly_objective_id'), table_name='weekly_objectives')
    op.drop_index(op.f('ix_weekly_objectives_id'), table_name='weekly_objectives')
    op.drop_index(op.f('ix_weekly_objectives_annual_goal_id'), table_name='weekly_objectives')
    op.drop_table('weekly_objectives')
    op.drop_index(op.f('ix_monthly_objectives_user_id'), table_name='monthly_objectives')
    op.drop_index(op.f('ix_monthly_objectives_id'), table_name='monthly_objectives')
    op.drop_index(op.f('ix_monthly_objectives_annual_goal_id'), table_name='monthly_objectives')
    op.drop_table('monthly_objectives')
    op.drop_index(op.f('ix_onboarding_insights_user_id'), table_name='onboarding_insights')
    op.drop_index(op.f('ix_onboarding_insights_id'), table_name='onboarding_insights')
    op.drop_table('onboarding_insights')
    op.drop_index(op.f('ix_life_area_scores_user_id'), table_name='life_area_scores')
    op.drop_index(op.f('ix_life_area_scores_id'), table_name='life_area_scores')
    op.drop_table('life_area_scores')
    op.drop_index(op.f('ix_annual_goals_user_id'), table_name='annual_goals')
    op.drop_index(op.f('ix_annual_goals_id'), table_name='annual_goals')
    op.drop_table('annual_goals')
    # ### end Alembic commands ###
