"""add_onboarding_fields_to_user_profile

Revision ID: 04b5dfff83e2
Revises: f3f663233f0d
Create Date: 2026-01-14 20:03:53.232558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04b5dfff83e2'
down_revision: Union[str, None] = 'f3f663233f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('onboarding_started_at', sa.DateTime(timezone=True), nullable=True, comment='When onboarding was started'))
    op.add_column('user_profiles', sa.Column('onboarding_current_step', sa.String(length=50), nullable=True, comment='Current onboarding step (welcome, name, goals, preferences, conclusion)'))
    op.add_column('user_profiles', sa.Column('onboarding_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Partial onboarding data (name, goals, preferences, conversation_history)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'onboarding_data')
    op.drop_column('user_profiles', 'onboarding_current_step')
    op.drop_column('user_profiles', 'onboarding_started_at')
    # ### end Alembic commands ###
