"""expand user profile and add calendar integration

Revision ID: 9bab0edad03c
Revises: 63a40d8ceeaf
Create Date: 2026-01-02 18:59:04.119723

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9bab0edad03c'
down_revision: str | None = '63a40d8ceeaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_integrations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE_CALENDAR', 'OUTLOOK', 'APPLE_CALENDAR', name='calendar_provider_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'TOKEN_EXPIRED', 'ERROR', 'DISCONNECTED', name='integration_status_enum', native_enum=False), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False, comment='Encrypted OAuth access token'),
    sa.Column('refresh_token', sa.Text(), nullable=False, comment='Encrypted OAuth refresh token'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False, comment='When the access token expires'),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False, comment='OAuth scopes granted by user'),
    sa.Column('calendars_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {calendar_id, calendar_name, color, include_in_planning}'),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False, comment='Whether automatic sync is enabled'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful sync timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message if any'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index(op.f('ix_calendar_integrations_id'), 'calendar_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_integrations_user_id'), 'calendar_integrations', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('morning_checkin_enabled', sa.Boolean(), nullable=False),
    sa.Column('morning_checkin_time', sa.Time(), nullable=False),
    sa.Column('evening_checkin_enabled', sa.Boolean(), nullable=False),
    sa.Column('evening_checkin_time', sa.Time(), nullable=False),
    sa.Column('weekly_review_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='week_day_enum', native_enum=False), nullable=False),
    sa.Column('week_start_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='week_day_enum', native_enum=False), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('communication_style', sa.Enum('DIRECT', 'GENTLE', 'MOTIVATING', name='communication_style_enum', native_enum=False), nullable=False),
    sa.Column('coach_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='onboarding_status_enum', native_enum=False), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vision_5_years', sa.Text(), nullable=True),
    sa.Column('vision_5_years_themes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('main_obstacle', sa.Text(), nullable=True),
    sa.Column('annual_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {id, description, area, created_at}'),
    sa.Column('observed_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {pattern_type, description, confidence, observed_at, evidence_count}'),
    sa.Column('moral_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Object with care, fairness, loyalty, authority, purity, liberty scores (0-1)'),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {id, description, category, source, confidence, evidence, created_at}'),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {id, name, type, engagement_level, related_to_goals, created_at}'),
    sa.Column('energy_activities', sa.ARRAY(sa.String()), nullable=True, comment='Activities that give energy'),
    sa.Column('drain_activities', sa.ARRAY(sa.String()), nullable=True, comment='Activities that drain energy'),
    sa.Column('satisfaction_health', sa.Integer(), nullable=True, comment='Health satisfaction score (1-10)'),
    sa.Column('satisfaction_work', sa.Integer(), nullable=True, comment='Work satisfaction score (1-10)'),
    sa.Column('satisfaction_relationships', sa.Integer(), nullable=True, comment='Relationships satisfaction score (1-10)'),
    sa.Column('satisfaction_personal_time', sa.Integer(), nullable=True, comment='Personal time satisfaction score (1-10)'),
    sa.Column('dashboard_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update of satisfaction scores'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('calendar_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False, comment='Event ID from external calendar provider'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('calendar_id', sa.String(length=500), nullable=False, comment='Calendar ID from external provider'),
    sa.Column('calendar_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('MEETING', 'FOCUS', 'PERSONAL', 'TRAVEL', 'OTHER', name='event_type_enum', native_enum=False), nullable=True, comment='Inferred event type (meeting, focus, etc.)'),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time this event was synced from provider'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['calendar_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'external_id', name='uq_integration_external_id')
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_integration_id'), 'calendar_events', ['integration_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_index('ix_calendar_events_user_start_time', 'calendar_events', ['user_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calendar_events_user_start_time', table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_integration_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_calendar_integrations_user_id'), table_name='calendar_integrations')
    op.drop_index(op.f('ix_calendar_integrations_id'), table_name='calendar_integrations')
    op.drop_table('calendar_integrations')
    # ### end Alembic commands ###
