"""widen_onboarding_status_for_setup_completed

Revision ID: ec0589172c60
Revises: 1cb056544d55
Create Date: 2026-03-07 15:33:42.653951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0589172c60'
down_revision: Union[str, None] = '1cb056544d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'context_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('ONBOARDING_SHORT', 'ONBOARDING_LONG', 'ONBOARDING_MODULE', 'PLANNING', 'CHECK_IN', 'REVIEW', 'FREE_CHAT', name='conversation_context_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE_CHAT'::character varying"))
    op.alter_column('user_profiles', 'onboarding_status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SETUP_COMPLETED', 'COMPLETED', name='onboarding_status_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'onboarding_status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SETUP_COMPLETED', 'COMPLETED', name='onboarding_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('conversations', 'context_type',
               existing_type=sa.Enum('ONBOARDING_SHORT', 'ONBOARDING_LONG', 'ONBOARDING_MODULE', 'PLANNING', 'CHECK_IN', 'REVIEW', 'FREE_CHAT', name='conversation_context_enum', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE_CHAT'::character varying"))
    # ### end Alembic commands ###
