"""add extra data for onboarding flow

Revision ID: 7a06b8bcb703
Revises: 4614361c5199
Create Date: 2026-02-01 21:25:37.928958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a06b8bcb703'
down_revision: Union[str, None] = '4614361c5199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('preferred_name', sa.String(length=100), nullable=True, comment="Como o usuário prefere ser chamado (ex: 'Má', 'Capitão')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferred_name')
    # ### end Alembic commands ###
