"""add contact frequency to user preferences

Revision ID: 4614361c5199
Revises: 9024015d71fc
Create Date: 2026-01-27 12:36:47.131435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4614361c5199'
down_revision: Union[str, None] = '9024015d71fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('contact_frequency', sa.Enum('RARELY', 'SOMETIMES', 'FREQUENTLY', name='contact_frequency_enum', native_enum=False), server_default='SOMETIMES', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'contact_frequency')
    # ### end Alembic commands ###
