"""add unique constraint to life_area_scores

Revision ID: 1cb056544d55
Revises: 73d2b72200f3
Create Date: 2026-02-22 14:22:00.067921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb056544d55'
down_revision: Union[str, None] = '73d2b72200f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_life_area_scores_user_area', 'life_area_scores', ['user_id', 'area'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_life_area_scores_user_area', 'life_area_scores', type_='unique')
    # ### end Alembic commands ###
