"""add subscription model

Revision ID: f3f663233f0d
Revises: 9bab0edad03c
Create Date: 2026-01-11 16:03:23.161095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f663233f0d'
down_revision: Union[str, None] = '9bab0edad03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'TRIAL', 'PAID', name='subscription_tier_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'TRIAL_ENDED', name='subscription_status_enum', native_enum=False), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='Subscription end date (NULL for FREE tier or unlimited PAID)'),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment='Trial period expiration (only for TRIAL tier)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)

    # Backfill FREE subscriptions for all existing users
    # This ensures all users created before this migration have a subscription
    op.execute("""
        INSERT INTO subscriptions (user_id, tier, status, start_date)
        SELECT id, 'FREE', 'ACTIVE', NOW()
        FROM users
        WHERE NOT EXISTS (
            SELECT 1 FROM subscriptions WHERE subscriptions.user_id = users.id
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
